### ISSUE TITLE
単体テストのログ対するマークル木構築が失敗します。

### ISSUE THREAD

**Issue by uriuriboo** [yebityon/POLDAM#10]
javaで書かれたソフトウェア実行トレースをとり、マークル木を構築することを想定しています。
mavenを使い一つのクラスに対して以下のように実行トレースを取ることを想定しているのですがこちらについてマークル木を構築できるように実装していただくことは可能でしょうか。

```
maven mvn -DargLine="-javaagent:path/to/selogger-0.5.0.jar=output=./selogger_out,format=omni,waverlog=hogehoeg_log.txt" test -D test=TestBasicAble
```

クラスは一つのみを指定することを想定しています。メゾットで指定することもあるかもしれません。
また、取得する実行トレースに関する質問ですがこちらの場合はSEloggerの`e=`オプションでjunitやmavenのログを取り除くべきでしょうか。

**Comment by yebityon** [comment]
おっと、すいません。僕の伝え方に問題があったようです。
Slackでの会話にもありましたが、もう少し詳細にお伝えします。

## issue の建て方

まずissueの建て方ですが、以下のような形式でissueを建ててくださると嬉しいです。
https://qiita.com/janus_wel/items/ba47259f107b161c5727
おおよそどのissueもこういうテンプレートになっているので、issueを建てる際は参考にしてください。厳密に従わなくても構いません。
例: https://github.com/takashi-ishio/selogger/issues/36 , https://github.com/takashi-ishio/selogger/issues/27

## 今回のissueに対して
### 粒度とissueに書くことについて
パッと見た限りですが、issueとして取り扱うには粒度が大きすぎます。
まずは上記のテンプレートに従って、問題を分割してください。また、issueは全世界から誰でも見れる内容となるため、
研究の内容及びヒントになるような内容を控えたほうが良いかもしれません。
例えば、`OSSの依存ライブラリのバージョンを上げることでテストに通らなくなったケースに対して実行トレースをとり`　といった背景は、研究の内容を含んでそうなので控えると良いかもしれません。また、issue の情報には必要ない気もします（もちろんあったほうが丁寧ですが、背景にしては大きすぎる/あんまり関係ない気もします)

### 具体的な情報の添付のお願い
上のセクションと内容が少し重複していますが、具体的な例があったほうが助かります。
例えば、
>mavenを使い一つのクラスに対して以下のように実行トレースを取ることを想定しているのですがこちらについてマークル木を構築できるように実装していただくことは可能でしょうか。

とありますが、複数に解釈できます。例えば、

- 現在その機能は有るが、特定のログに対してPOLDAMがマークル木の構築について失敗している(ので改善してほしい)
- 現在その機能は無いため、上記のコマンドによって出力されるログ形式についてPOLDAMが対応してほしい

などです。具体例を用いて説明されていると、読み手がどちらかなのか対応できます。


>クラスは一つのみを指定することを想定しています。メゾットで指定することもあるかもしれません。
また、取得する実行トレースに関する質問ですがこちらの場合はSEloggerのe=オプションでjunitやmavenのログを取り除くべきでしょうか。

基本的には一つのissueには一つの質問にするのがベターです。今回は内容が重複してそうなのでもんだいりません。
この質問の意図は、どういったものなのでしょうか？
POLDAMは入力として `取得する実行トレースに関する質問ですがこちらの場合はSEloggerのe=オプションでjunitやmavenのログを取り除いたもの`を前提としているかどうか？という感じでしょうか？
と言うのであれば、答えはNoです。特別な前処理を必要としない前提で作成しています

**Comment by uriuriboo** [comment]
不適切な書き方をしてしまい大変失礼いたしました。以下に簡潔に書き直したのものをコメントさせていただきます。
また、issueの書き方の大して懇切丁寧に指摘していただき誠にありがとうございます。

# 説明
mavenを用いて単体テストを行った実装トレースををSEloggerを用いて取得したところマークル木の構築においてSegmentaion faultを起こすため改善をお願いいたします。
Seloggerのログについてはjunitやmavenを取り除かない者を想定しています。

**Comment by uriuriboo** [comment]
centos上で動作することを確認しました。ありがとうございました。
